spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db_payroll"
    username: AnatoliiHamza
    password: 123Anatolii
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
  liquibase:
    change-log: "classpath:database/liquibase/liquibase-changeLog.xml"

